### ISSUE TITLE
BUG? servers > address 支持数组?

### ISSUE THREAD

**Issue by gowy222** [DustinWin/ruleset_geodata#13]
看到很多类似:
"servers": [
      { "tag": "dns_direct", "address": [ "https://doh.pub/dns-query", "https://dns.alidns.com/dns-query" ], "detour": "DIRECT" },
address支持数组?

但是源码
https://github.com/SagerNet/sing-box/blob/327df8cab6ad1a3a977aa5d94f2109b7d84c2459/option/dns.go#L16
对应的类型是string?

**Comment by DustinWin** [comment]
请仔细看描述：  
![QQ20240729-180341](https://github.com/user-attachments/assets/d1332be6-91ed-4881-9bd2-b883c027984e)
