### ISSUE TITLE
singbox-p内核 domain_suffix规则匹配不了二级域名

### ISSUE THREAD

**Issue by psychosispy** [DustinWin/ruleset_geodata#6]
x.com无法匹配,1.x.com可以匹配,符合预期吗
singbox-p内核好像不支持1.9新特性

**Comment by psychosispy** [comment]
https://github.com/SagerNet/sing-box/blob/cc8ae725c801419d9926951951816e9ac6ca67d0/docs/migration.zh.md?plain=1#L11

**Comment by psychosispy** [comment]
应该是你的规则搞错了      
>domain_suffix:.baidu.com 可以匹配 baidu.com 和 baike.baidu.com

应该是baidu.com 可以匹配 baidu.com 和 baike.baidu.com
.baidu.com只能匹配baike.baidu.com

**Comment by OsemDing** [comment]
> 应该是你的规则搞错了
> 
> > domain_suffix:.baidu.com 可以匹配 baidu.com 和 baike.baidu.com
> 
> 应该是baidu.com 可以匹配 baidu.com 和 baike.baidu.com .baidu.com只能匹配baike.baidu.com

应该是1.9后更改了，我也发现claude.ai匹配不了，把前面的点去掉就可以了

**Comment by DustinWin** [comment]
感谢提醒，理解错了，已经修改。
